#!/usr/bin/env bash
set -euo pipefail

PROJECT_ROOT="${PROJECT_ROOT:-$PWD}"
ENV_FILE="${ENV_FILE:-$PROJECT_ROOT/.env}"

cd "$PROJECT_ROOT"

echo "This writes secrets to $ENV_FILE with chmod 600."
echo "Input is hidden. Leave blank to skip a field."

read -r -s -p "PAVE_TEACHER_API_KEY: " PAVE_TEACHER_API_KEY
echo
read -r -p "PAVE_TEACHER_API_BASE: " PAVE_TEACHER_API_BASE
read -r -p "PAVE_TEACHER_MODEL: " PAVE_TEACHER_MODEL
read -r -s -p "HF_TOKEN: " HF_TOKEN
echo

umask 077
{
  echo "# Generated by set_server_secrets.sh"
  echo "PAVE_TEACHER_API_KEY=${PAVE_TEACHER_API_KEY}"
  echo "PAVE_TEACHER_API_BASE=${PAVE_TEACHER_API_BASE}"
  echo "PAVE_TEACHER_MODEL=${PAVE_TEACHER_MODEL}"
  echo "HF_TOKEN=${HF_TOKEN}"
} > "$ENV_FILE"

chmod 600 "$ENV_FILE"
echo "Wrote $ENV_FILE"

if [[ -n "${HF_TOKEN}" ]]; then
  source "$ENV_FILE"
  if command -v huggingface-cli >/dev/null 2>&1; then
    huggingface-cli login --token "$HF_TOKEN" || true
  fi
fi

