"""Import the user's Word and Excel question bank without third-party readers."""
import json
import re
import zipfile
from pathlib import Path
from xml.etree import ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
WORD_NS = '{http://schemas.openxmlformats.org/wordprocessingml/2006/main}'
SHEET_NS = {'s': 'http://schemas.openxmlformats.org/spreadsheetml/2006/main'}

DIMENSIONS = [
    ('explore', '未知探索', '熟悉可靠', '探索陌生'),
    ('order', '节奏规划', '临场发挥', '提前安排'),
    ('logic', '观点坚持', '照顾感受', '理清逻辑'),
    ('imagine', '脑洞联想', '直接行动', '追问可能'),
    ('social', '社交能量', '安静独处', '主动连接'),
    ('steady', '自我笃定', '在意比较', '相信节奏'),
    ('purpose', '内心热望', '随境调整', '坚持热爱'),
    ('freedom', '规则自由', '遵循常规', '改写规则'),
    ('boundary', '独立空间', '亲密共享', '保留边界'),
    ('focus', '目标定力', '沿途发现', '奔向目标'),
]
# Which answer points to the right end of a dimension. This is a creative
# entertainment rubric, not a validated psychological inventory.
HIGH = {
    1: 'BBAB', 2: 'ABAA', 3: 'AAAA', 4: 'AABB', 5: 'AAAA',
    6: 'BAAA', 7: 'BBBA', 8: 'BBBB', 9: 'AAAA', 10: 'AAAA',
}


def import_questions():
    questions = []
    source = next(ROOT.glob('*.docx'))
    with zipfile.ZipFile(source) as archive:
        root = ET.fromstring(archive.read('word/document.xml'))
        lines = [
            ''.join(t.text or '' for t in p.iter(WORD_NS + 't')).strip()
            for p in root.iter(WORD_NS + 'p')
        ]
    lines = [line for line in lines if line]
    for index, line in enumerate(lines):
        match = re.fullmatch(r'(\d+)\.(\d+)', line)
        if match:
            dimension, item = map(int, match.groups())
            questions.append(make_question(dimension, item, lines[index + 1],
                                          lines[index + 2], lines[index + 3], source.name))

    source = next(ROOT.glob('*.xlsx'))
    with zipfile.ZipFile(source) as archive:
        strings = [''.join(n.itertext()) for n in ET.fromstring(archive.read('xl/sharedStrings.xml'))]
        sheet = ET.fromstring(archive.read('xl/worksheets/sheet1.xml'))
        for cell in sheet.findall('.//s:c', SHEET_NS):
            match = re.fullmatch(r'([ACE])([2-5])', cell.get('r', ''))
            value = cell.find('s:v', SHEET_NS)
            if not match or value is None:
                continue
            column, row = match.groups()
            dimension, item = {'A': 4, 'C': 5, 'E': 6}[column], int(row) - 1
            text = strings[int(value.text)] if cell.get('t') == 's' else value.text
            parts = text.strip().splitlines()
            questions.append(make_question(dimension, item, parts[0], parts[1], parts[2], source.name))

    # Interleave the ten source groups so each act samples the whole profile.
    questions.sort(key=lambda q: (int(q['id'].split('.')[1]), int(q['id'].split('.')[0])))
    assert len(questions) == 40
    assert len({q['id'] for q in questions}) == 40
    output = ROOT / 'src' / 'data' / 'questions.js'
    output.parent.mkdir(parents=True, exist_ok=True)
    dimensions = [dict(id=d, label=label, low=low, high=high) for d, label, low, high in DIMENSIONS]
    output.write_text('// Generated by scripts/import_questions.py. Preserve source wording.\n'
                      + 'export const dimensions = ' + json.dumps(dimensions, ensure_ascii=False, indent=2) + ';\n\n'
                      + 'export const questions = ' + json.dumps(questions, ensure_ascii=False, indent=2) + ';\n', encoding='utf-8')
    print(f'Imported {len(questions)} questions and {len(dimensions)} dimensions.')


def make_question(dimension, item, prompt, option_a, option_b, source):
    # Excel A3 asks about starting a conversation. Score it as social energy
    # instead of imagination; dimension totals are normalized separately.
    scored_dimension = 5 if (dimension, item) == (4, 2) else dimension
    return {
        'id': f'{dimension}.{item}',
        'dimension': DIMENSIONS[scored_dimension - 1][0],
        'prompt': prompt,
        'options': [re.sub(r'^[AB][.．、]\s*', '', option_a), re.sub(r'^[AB][.．、]\s*', '', option_b)],
        'highAnswer': HIGH[dimension][item - 1],
        'source': source,
    }


if __name__ == '__main__':
    import_questions()
